/*
    This program gives a simple example of how a process
    can catch a signal.  Here, SIGINT signals (typically
    generated by the user hitting CTL-C) are caught.

    Recall that if you have a PID, you can stop it with the command:

       kill PID
*/

#include <signal.h>
#include <stdio.h>
#include <unistd.h>

const long limit = 20000000000;
const long frequency = 50000000;

void interrupt_handler(int);

int main()
{
    long i;

    pid_t process_id = getpid();

    /* The initial handler for the SIGINT signal is
       assuredly the default, so confusion will not reign */
    if (signal(SIGINT, interrupt_handler) != SIG_DFL) // register for CTRL-C
    {
        fprintf(stderr, "I'm confused.\n");
    }

    /* Start counting */
    for (i = 0; i < limit; i++)
    {
        if (i % frequency == 0)
        {
            fprintf(stderr, "[PID %d] %ld\n", process_id, i);
            fflush(stderr);
        }
    }

    return 0;
}

// Handle registered interrupts
void interrupt_handler(int sig)
{
    fprintf(stderr, "Sorry, but I just don't want to quit.\n");
    fflush(stderr);
}